//  Helium.swift
//  Created by Umur Gedik on 17.01.2022.

import Foundation

#if DEBUG
fileprivate let heliumJSON = """
{
  "number": 2,
  "name_tr": "Helyum",
  "name_en": "Helium",
  "alternate_name": "",
  "symbol": "He",
  "cas_number": "7440-59-7",
  "cid_number": "CID23987",
  "dot_number": "1963",
  "rtecs_number": "RTECSMH6520000",
  "mendeleev_number": 112,
  "pettifor_number": 1,
  "eu_number": "",
  "space_group_number": "225",
  "glawe_number": 1,
  "atomic_mass": "4.0026022",
  "atomic_mass_uncertainty": "0.00000200",
  "xpos": 18,
  "ypos": 1,
  "period": 1,
  "group": "18",
  "block": "s",
  "category": "soy gaz",
  "electrical_type": "",
  "geochemical_class": "Uçucu",
  "goldschmidt_class": "Atmofil",
  "gas_phase": "Monoatomik",
  "allotrope_names": "",
  "appearance": "renksiz gaz, yüksek voltajlı elektrik alana yerleştirildiğinde kırmızı-turuncu parlar",
  "abundance_in_earth_crust_c1": "0.0000000080",
  "abundance_in_earth_crust_c2": "",
  "abundance_in_earth_crust_c3": "",
  "abundance_in_earth_crust_c4": "",
  "abundance_in_earth_crust_c5": "",
  "abundance_in_earth_crust_c6": "",
  "abundance_in_earth_crust_u1": "",
  "abundance_in_earth_crust_u2": "",
  "abundance_urban_soil": "0.0000",
  "abundance_meteorite": "N/A",
  "abundance_seawater_w1": "0.0000000000070",
  "abundance_seawater_w2": "0.0000000000072",
  "abundance_humans": "",
  "abundance_in_humans_2": "",
  "abundance_sun_s1": "2,700",
  "abundance_solar_system_y1": "2,700",
  "abundance_solar_system_y2": "2,720",
  "atomic_radius_empirical": "120",
  "atomic_radius_calculated": "31",
  "atomic_radius_vanderwaals": "140",
  "vdw_radius_bondi": "140",
  "vdw_radius_truhlar": "",
  "vdw_radius_rt": "",
  "atomic_radius_rahm": "134",
  "vdw_radius_batsanov": "",
  "vdw_radius_dreiding": "",
  "vdw_radius_uff": "236.2",
  "vdw_radius_mm3": "153",
  "vdw_radius_alvarez": "143",
  "covalent_radius_bragg": "",
  "atomic_radius_covalent_single_bond": "32",
  "atomic_radius_covalent_triple_bond": "",
  "covalent_radius_cordero": "28",
  "covalent_radius_pyykko": 46,
  "covalent_radius_pyykko_double": "",
  "covalent_radius_pyykko_triple": "",
  "metallic_radius_mendeleev": "",
  "metallic_radius_c12": "122",
  "atomic_radius_metallic": "",
  "jmol_color": "d9ffff",
  "molcas_gv_color": "d9ffff",
  "cpk_color": "ffc0cb",
  "refractive_index": "1.000035",
  "phase_at_stp": "Gaz",
  "melt_use": "0.95",
  "melt_WEL": "0.95",
  "melt_CRC": "",
  "melt_LNG": "0.85",
  "boil_use": "4.222",
  "boil_WEL": "4.22",
  "boil_CRC": "4.072",
  "boil_LNG": "4.065",
  "boil_Zhang": "4",
  "curie_point": "",
  "critical_temperature": "5.19",
  "flashpoint": "",
  "superconducting_point": "",
  "autoignition_point": "",
  "critical_pressure": "0.227",
  "density_rt": "0.1786",
  "density_solid_WEL": "",
  "density_solid_LNG": "",
  "density_solid_CRC": "",
  "density_liquid_cr2": "",
  "density_gas": "0.1786",
  "molar_volume": "22,413.60",
  "atomic_volume": "31.8",
  "enthalpy_of_fusion": "",
  "heat_of_fusion_crc": "",
  "heat_of_fusion_lng": "0.0138",
  "heat_of_fusion_wel": "0.02",
  "evaporation_heat": "0.08",
  "heat_of_vaporization_crc": "0.08",
  "heat_of_vaporization_lng": "0.0829",
  "heat_of_vaporization_wel": "0.083",
  "heat_of_vaporization_zhang": "",
  "heat_of_combustion": "",
  "molar_heat": "",
  "specific_heat_capacity": "5.188",
  "specific_heat_crc": "20.786",
  "specific_heat_wel": "20.786",
  "specific_heat_lng": "20.786",
  "thermal_conductivity": "0.152",
  "thermal_expansion": "",
  "adiabatic_index": "42799",
  "speed_of_sound_longitudinal": "",
  "speed_of_sound_transversal": "",
  "speed_of_sound_extensional": "",
  "speed_of_sound_fluid": "965",
  "electrical_resistivity_80K": "",
  "electrical_resistivity_273K": "",
  "electrical_resistivity_293K": "",
  "electrical_resistivity_298K": "",
  "electrical_resistivity_300K": "",
  "electrical_resistivity_500K": "",
  "magnetic_ordering": "Diyamanyetik",
  "neel_point": "",
  "magnetic_susceptibility": "-0.0000000059",
  "shear_modulus": "",
  "bulk_modulus": "",
  "poisson_ratio": "",
  "youngs_modulus": "",
  "mohs_hardness": "",
  "brinell_hardness": "",
  "vickers_hardness": "",
  "description": "Renksiz, kokusuz, gaz halde bulunan bir ametal elementtir. Periyodik tabloda 18.gruba aittir. Bütün elementler arasında en düşük kaynama noktasına sahip olup sadece baskı uygulanırsa katılaştırılabilir. Kimyasal olarak atıldır ve bilinen bir bileşiği yoktur. 1868 yılında Lockyer tarafından güneş spektrumunda keşfedilmiştir.",
  "language_of_origin": "Yunanca",
  "origin_of_word": "Yunanca'da \\"güneş\\" anlamına gelen helios sözcüğünden",
  "original_word": "ἥλιος (hélios)",
  "meaning": "güneş",
  "symbol_origin": "astrolojik, mitolojik",
  "etymological_description": "Yunanca'da \\"güneş\\" veya mitolojik güneş tanrısı anlamındaki helios sözcüğünden türemiştir.",
  "observed_predicted_by": "P. Janssen ve N. Lockyer",
  "observation_or_discovery_year": "1868",
  "discovery_location": "İskoçya/İsveç",
  "isolated_sampled_by": "W. Ramsay, T. Cleve, ve N. Langlet",
  "isolation_sample_year": "1895",
  "named_by": "",
  "sources": "Doğal gaz yataklarında ve havada (5 ppb oranında) bulunur. Devamlı olarak uzayda kaybolur ve radyoaktif bozunma (alfa parçacıkları) ile tazelenir.",
  "uses": "Balonlarda, derin dalışta ve kaynakçılıkta kullanılır. Aynı zamanda düşük sıcaklık gereken araştırmalarda kullanılır.",
  "spectral_img": "https://en.wikipedia.org/wiki/File:Helium_spectrum.jpg",
  "is_radioactive": 0,
  "decay_mode": "",
  "half_life": "Stabil",
  "lifetime": "Stabil",
  "neutron_mass_absorption": "0.00001",
  "neutron_cross_section": "0.01",
  "proton_affinity": "177.8",
  "electron_affinity_eV": "-19.7",
  "electron_affinity_kJmol": "-48",
  "electronegativity_pauling": "",
  "electronegativity_allen": "24.59",
  "electronegativity_ghosh": "0.442712",
  "dipole_polarizability": "1.38375",
  "dipole_polarizability_unc": "0.00002",
  "c6_gb": "1.47",
  "c6_coeff": "1.42",
  "lattice_constant_internal_default_radii": "3.57",
  "lattice_constant": "424.2, 424.2, 424.2",
  "lattice_structure": "HEX",
  "lattice_angles": "π/2, π/2, π/2",
  "oxidation_states": "",
  "electron_configuration": "1s2",
  "quantum_number": "1S0",
  "electron_configuration_semantic": "1s2",
  "shells-0": 2,
  "shells-1": null,
  "shells-2": null,
  "shells-3": null,
  "shells-4": null,
  "shells-5": null,
  "shells-6": null,
  "shells-7": null,
  "ionization_energies-0": "2372.3",
  "ionization_energies-1": "5250.5",
  "ionization_energies-2": "",
  "ionization_energies-3": "",
  "ionization_energies-4": "",
  "ionization_energies-5": "",
  "ionization_energies-6": "",
  "ionization_energies-7": "",
  "ionization_energies-8": "",
  "ionization_energies-9": "",
  "ionization_energies-10": "",
  "ionization_energies-11": "",
  "ionization_energies-12": "",
  "ionization_energies-13": "",
  "ionization_energies-14": "",
  "ionization_energies-15": "",
  "ionization_energies-16": "",
  "ionization_energies-17": "",
  "ionization_energies-18": "",
  "ionization_energies-19": "",
  "ionization_energies-20": "",
  "ionization_energies-21": "",
  "ionization_energies-22": "",
  "ionization_energies-23": "",
  "ionization_energies-24": "",
  "ionization_energies-25": "",
  "ionization_energies-26": "",
  "ionization_energies-27": "",
  "ionization_energies-28": "",
  "ionization_energies-29": "",
  "wikipedia": "https://en.wikipedia.org/wiki/Helium",
  "ea_content_id": 9848
}
"""

public let previewHeliumElement: Element = try! {
    do {
        return try JSONDecoder().decode(Element.self, from: heliumJSON.data(using: .utf8)!)
    } catch let error as DecodingError {
        print(error)
        throw error
    }
}()
#endif
